name: propview
description: A new Flutter project.

publish_to: 'none'

version: 1.0.45+46

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  api_cache_manager: 
  camera: 
  collection: 
  cupertino_icons: 
  double_back_to_close_app: 
  firebase_analytics: 
  firebase_core:
  firebase_messaging: 
  fl_chart: 
  flutter:
    sdk: flutter
  flutter_datetime_picker: 
  flutter_html_to_pdf: 
  flutter_image_compress: 
  flutter_local_notifications: 
  flutter_picker: 
  flutter_speed_dial: 
  flutter_typeahead: 
  geolocator: 
  google_fonts: 
  google_nav_bar: 
  http: 
  image_cropper: 
  image_picker: 
  intl: 
  path_provider: 
  provider: 
  share_plus: 
  shared_preferences: 
  syncfusion_flutter_calendar: 
  timeago: 
  update_app:
  url_launcher: 
  webview_flutter: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/inspection/
    - assets/tenant/
